steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/glucoguard-t1d'
      - '.'

substitutions:
  _NEXT_PUBLIC_FIREBASE_API_KEY: 'placeholder-key'
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: 'placeholder-domain'
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: 'placeholder-project-id'
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: 'placeholder-bucket'
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 'placeholder-sender-id'
  _NEXT_PUBLIC_FIREBASE_APP_ID: 'placeholder-app-id'
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: 'placeholder-measurement-id'

images:
  - 'gcr.io/$PROJECT_ID/glucoguard-t1d'

options:
  logging: CLOUD_LOGGING_ONLY