# Stage 2: Build the application
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Declare build arguments for Next.js public variables
ARG _NEXT_PUBLIC_FIREBASE_API_KEY
ARG _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG _NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG _NEXT_PUBLIC_FIREBASE_APP_ID
ARG _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

# Map build args to actual env vars Next.js expects (no leading underscore)
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$_NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$_NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$_NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
RUN npm run build